jsxRuntime: automatic
filenameCase: kebab
titleProp: true
svgProps:
  fill: currentColor
svgoConfig:
    plugins:
      -
        name: preset-default
        params:
          overrides:
            removeViewBox: false
